import { DocumentItem, DocumentResultsResponse, LineItem } from '@/types/document';
import { AuditLog } from '@/types/audit';

export const DEMO_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-tata-steel-9041',
    document_id: 'doc-tata-steel-9041',
    filename: 'Tax_Invoice_Tata_Steel_INV9041.pdf',
    original_filename: 'Tax_Invoice_Tata_Steel_INV9041.pdf',
    document_type: 'GST Invoice',
    upload_date: '2026-10-09T08:15:20Z',
    status: 'VERIFIED',
    overall_confidence: 96,
    file_size: 1420500,
    page_count: 2,
    uploaded_by: {
      id: 'usr-1',
      name: 'Rajesh Sharma, FCA',
      email: 'rajesh.ca@sharmaassociates.in',
    },
    created_at: '2026-10-09T08:15:20Z',
    updated_at: '2026-10-09T08:25:10Z',
  },
  {
    id: 'doc-ganesh-kachha-102',
    document_id: 'doc-ganesh-kachha-102',
    filename: 'Kachha_Bill_Shree_Ganesh_Traders_Oct2026.png',
    original_filename: 'Kachha_Bill_Shree_Ganesh_Traders_Oct2026.png',
    document_type: 'Hindi Handwritten Receipt / Kachha Bill',
    upload_date: '2026-10-09T08:45:10Z',
    status: 'NEEDS_REVIEW',
    overall_confidence: 68,
    file_size: 2840100,
    page_count: 1,
    uploaded_by: {
      id: 'usr-2',
      name: 'Priya Verma',
      email: 'priya.accts@sharmaassociates.in',
    },
    review_notes: 'OCR confidence 64% on total handwritten amount; please verify ₹18,450 vs ₹18,950.',
    created_at: '2026-10-09T08:45:10Z',
    updated_at: '2026-10-09T08:46:00Z',
  },
];

export const DEMO_RESULTS: Record<string, DocumentResultsResponse> = {
  'doc-tata-steel-9041': {
    document_id: 'doc-tata-steel-9041',
    document_type: 'GST Invoice',
    overall_confidence: 96,
    status: 'VERIFIED',
    file_url: '/samples/sample-invoice.pdf',
    mime_type: 'application/pdf',
    page_count: 2,
    fields: [
      {
        field_key: 'supplier_name',
        label: 'Supplier Legal Name',
        normalized_value: 'Tata Steel Processing & Distribution Limited',
        original_ocr_value: 'TATA STEEL PROCESSING & DISTRIBUTION LTD',
        confidence: 98,
        validation_state: 'valid',
        bounding_box: { x_min: 75, y_min: 110, x_max: 340, y_max: 135, page: 1 },
        category: 'party',
        page: 1,
      },
      {
        field_key: 'supplier_gstin',
        label: 'Supplier GSTIN',
        normalized_value: '27AAACT2727Q1ZB',
        original_ocr_value: '27AAACT2727Q1ZB',
        confidence: 99,
        validation_state: 'valid',
        bounding_box: { x_min: 75, y_min: 140, x_max: 220, y_max: 160, page: 1 },
        category: 'party',
        page: 1,
      },
      {
        field_key: 'buyer_name',
        label: 'Buyer Name (Billed To)',
        normalized_value: 'Apex Precision Engineering Solutions Pvt Ltd',
        original_ocr_value: 'Apex Precision Engg Solutions P. Ltd.',
        confidence: 95,
        validation_state: 'valid',
        bounding_box: { x_min: 75, y_min: 190, x_max: 320, y_max: 215, page: 1 },
        category: 'party',
        page: 1,
      },
      {
        field_key: 'buyer_gstin',
        label: 'Buyer GSTIN',
        normalized_value: '07AABCA1234D1ZP',
        original_ocr_value: '07AABCA1234D1ZP',
        confidence: 97,
        validation_state: 'valid',
        bounding_box: { x_min: 75, y_min: 220, x_max: 210, y_max: 240, page: 1 },
        category: 'party',
        page: 1,
      },
      {
        field_key: 'invoice_number',
        label: 'Tax Invoice Number',
        normalized_value: 'TSPDL/MUM/2026/9041',
        original_ocr_value: 'TSPDL/MUM/2026/9041',
        confidence: 98,
        validation_state: 'valid',
        bounding_box: { x_min: 420, y_min: 110, x_max: 560, y_max: 130, page: 1 },
        category: 'general',
        page: 1,
      },
      {
        field_key: 'invoice_date',
        label: 'Invoice Date',
        normalized_value: '2026-10-04',
        original_ocr_value: '04/10/2026',
        confidence: 96,
        validation_state: 'valid',
        bounding_box: { x_min: 420, y_min: 140, x_max: 520, y_max: 160, page: 1 },
        category: 'general',
        page: 1,
      },
      {
        field_key: 'place_of_supply',
        label: 'Place of Supply (State)',
        normalized_value: '07 - Delhi',
        original_ocr_value: 'Delhi (07)',
        confidence: 92,
        validation_state: 'valid',
        bounding_box: { x_min: 420, y_min: 170, x_max: 510, y_max: 190, page: 1 },
        category: 'tax',
        page: 1,
      },
      {
        field_key: 'hsn_code',
        label: 'HSN / SAC Code',
        normalized_value: '7208',
        original_ocr_value: '7208 38 40',
        confidence: 76,
        validation_state: 'warning',
        validation_message: '4-digit HSN detected; MSME requires 6-digit HSN for >₹5 Cr turnover',
        bounding_box: { x_min: 75, y_min: 310, x_max: 140, y_max: 330, page: 1 },
        category: 'tax',
        page: 1,
      },
      {
        field_key: 'taxable_amount',
        label: 'Taxable Amount (₹)',
        normalized_value: '210500.00',
        original_ocr_value: '2,10,500.00',
        confidence: 96,
        validation_state: 'valid',
        bounding_box: { x_min: 440, y_min: 420, x_max: 550, y_max: 440, page: 1 },
        category: 'totals',
        page: 1,
      },
      {
        field_key: 'igst_amount',
        label: 'Integrated GST (IGST @ 18%)',
        normalized_value: '37890.00',
        original_ocr_value: '37,890.00',
        confidence: 95,
        validation_state: 'valid',
        bounding_box: { x_min: 440, y_min: 450, x_max: 550, y_max: 470, page: 1 },
        category: 'totals',
        page: 1,
      },
      {
        field_key: 'cgst_amount',
        label: 'Central GST (CGST)',
        normalized_value: '0.00',
        original_ocr_value: '0.00',
        confidence: 99,
        validation_state: 'valid',
        category: 'totals',
        page: 1,
      },
      {
        field_key: 'sgst_amount',
        label: 'State GST (SGST)',
        normalized_value: '0.00',
        original_ocr_value: '0.00',
        confidence: 99,
        validation_state: 'valid',
        category: 'totals',
        page: 1,
      },
      {
        field_key: 'total_amount',
        label: 'Total Invoice Amount (INR)',
        normalized_value: '248390.00',
        original_ocr_value: '2,48,390.00',
        confidence: 97,
        validation_state: 'valid',
        bounding_box: { x_min: 440, y_min: 490, x_max: 550, y_max: 515, page: 1 },
        category: 'totals',
        page: 1,
      },
    ],
    line_items: [
      {
        id: 'li-1',
        description: 'HR Steel Coils 2.5mm Grade IS 2062 E250',
        hsn_sac: '72083840',
        quantity: 3.5,
        unit_price: 60142.86,
        taxable_amount: 210500.0,
        igst_rate: 18,
        total: 248390.0,
        confidence: 95,
      },
    ],
    metadata: {
      processing_time_ms: 1840,
      model_version: 'BharatDoc-Multimodal-v2.6',
      ocr_engine: 'DeepVision-OCR-Indic',
      detected_language: 'English',
    },
  },

  'doc-ganesh-kachha-102': {
    document_id: 'doc-ganesh-kachha-102',
    document_type: 'Hindi Handwritten Receipt / Kachha Bill',
    overall_confidence: 68,
    status: 'NEEDS_REVIEW',
    file_url: '/samples/sample-kachha-bill.png',
    mime_type: 'image/png',
    page_count: 1,
    fields: [
      {
        field_key: 'supplier_name',
        label: 'विक्रेता / फर्म का नाम (Supplier)',
        normalized_value: 'श्री गणेश ट्रेडर्स (Shree Ganesh Traders)',
        original_ocr_value: 'श्री गनेश टेडर्स',
        confidence: 82,
        validation_state: 'valid',
        bounding_box: { x_min: 60, y_min: 70, x_max: 310, y_max: 105, page: 1 },
        category: 'party',
        page: 1,
      },
      {
        field_key: 'mandi_license_no',
        label: 'मंडी अनुज्ञप्ति सं. / License No.',
        normalized_value: 'UP/KNP/MND/4412',
        original_ocr_value: 'UP 4412',
        confidence: 72,
        validation_state: 'warning',
        validation_message: 'Handwritten prefix auto-completed from Mandi database',
        bounding_box: { x_min: 60, y_min: 110, x_max: 200, y_max: 130, page: 1 },
        category: 'party',
        page: 1,
      },
      {
        field_key: 'receipt_number',
        label: 'पर्चा संख्या (Slip / Bill No)',
        normalized_value: '1048',
        original_ocr_value: '१०४८',
        confidence: 78,
        validation_state: 'valid',
        bounding_box: { x_min: 360, y_min: 70, x_max: 430, y_max: 95, page: 1 },
        category: 'general',
        page: 1,
      },
      {
        field_key: 'date',
        label: 'दिनांक (Date)',
        normalized_value: '2026-10-08',
        original_ocr_value: '८/१०/२६',
        confidence: 88,
        validation_state: 'valid',
        bounding_box: { x_min: 360, y_min: 100, x_max: 450, y_max: 125, page: 1 },
        category: 'general',
        page: 1,
      },
      {
        field_key: 'item_description',
        label: 'विवरण / जिंस (Commodity)',
        normalized_value: 'सरसों दाना (Mustard Seeds) - 12 बोरी',
        original_ocr_value: 'सरसो दाना १२ बोरी',
        confidence: 84,
        validation_state: 'valid',
        bounding_box: { x_min: 60, y_min: 180, x_max: 250, y_max: 210, page: 1 },
        category: 'general',
        page: 1,
      },
      {
        field_key: 'total_amount',
        label: 'कुल राशि (Total Amount in ₹)',
        normalized_value: '18450.00',
        original_ocr_value: '१८,४५० / १८,९५० ?',
        confidence: 62,
        validation_state: 'error',
        validation_message: 'CRITICAL: Ambiguous Devanagari digit (४ vs ९). Low confidence (62%). Requires Human Verification.',
        bounding_box: { x_min: 340, y_min: 320, x_max: 460, y_max: 355, page: 1 },
        category: 'totals',
        page: 1,
      },
      {
        field_key: 'hamali_charges',
        label: 'हमाली / पल्लेदारी शुल्क (Labour)',
        normalized_value: '350.00',
        original_ocr_value: '३५०',
        confidence: 81,
        validation_state: 'valid',
        bounding_box: { x_min: 340, y_min: 270, x_max: 420, y_max: 295, page: 1 },
        category: 'totals',
        page: 1,
      },
    ],
    metadata: {
      processing_time_ms: 2420,
      model_version: 'BharatDoc-Indic-Handwriting-v3.1',
      ocr_engine: 'Indic-Bhasha-Vision',
      detected_language: 'Hindi (Devanagari script)',
    },
  },
};

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-109',
    timestamp: '2026-10-09T08:25:10Z',
    actor: {
      id: 'usr-1',
      name: 'Rajesh Sharma, FCA',
      role: 'CHARTERED_ACCOUNTANT',
      email: 'rajesh.ca@sharmaassociates.in',
    },
    action: 'APPROVE_DOCUMENT',
    document_id: 'doc-tata-steel-9041',
    document_name: 'Tax_Invoice_Tata_Steel_INV9041.pdf',
    notes: 'Verified against GSTR-2B inward supplies ledger. ITC eligibility confirmed.',
    ip_address: '103.24.18.92',
  },
  {
    id: 'aud-108',
    timestamp: '2026-10-09T08:24:45Z',
    actor: {
      id: 'usr-1',
      name: 'Rajesh Sharma, FCA',
      role: 'CHARTERED_ACCOUNTANT',
      email: 'rajesh.ca@sharmaassociates.in',
    },
    action: 'EDIT_FIELD',
    document_id: 'doc-tata-steel-9041',
    document_name: 'Tax_Invoice_Tata_Steel_INV9041.pdf',
    field_key: 'hsn_code',
    before_value: '7208',
    after_value: '72083840',
    reason: 'Updated to standard 8-digit tariff item for e-Invoice compliance.',
    ip_address: '103.24.18.92',
  },
  {
    id: 'aud-107',
    timestamp: '2026-10-09T08:15:20Z',
    actor: {
      id: 'usr-1',
      name: 'Rajesh Sharma, FCA',
      role: 'CHARTERED_ACCOUNTANT',
      email: 'rajesh.ca@sharmaassociates.in',
    },
    action: 'UPLOAD',
    document_id: 'doc-tata-steel-9041',
    document_name: 'Tax_Invoice_Tata_Steel_INV9041.pdf',
    notes: 'Uploaded 2-page GST Tax Invoice batch via web portal.',
    ip_address: '103.24.18.92',
  },
  {
    id: 'aud-106',
    timestamp: '2026-10-08T16:45:00Z',
    actor: {
      id: 'usr-2',
      name: 'Priya Verma',
      role: 'ACCOUNTANT',
      email: 'priya.accts@sharmaassociates.in',
    },
    action: 'EXPORT_TALLY',
    document_id: 'doc-tata-steel-9041',
    document_name: 'Tax_Invoice_Tata_Steel_INV9041.pdf',
    notes: 'Generated Tally Prime XML Purchase Voucher format.',
    ip_address: '103.24.18.94',
  },
];
